# Default values for fhir-storage-writer.
debug:
  enable: false

# Number of Pod Replicas desired
replicaCount: 1

# Required Values for the Chart
required:
  # Define the docker image
  image:
    # The repository where is stored the docker image "fhir-storage-writer"
    repository: europe-west3-docker.pkg.dev/gematik-all-infra-prod/demis-dev
    # The name of the image
    name: fhir-storage-writer
    # Overrides the image tag whose default is the chart appVersion. 
    # If not given, the Chart AppVersion will be used
    tag: null

customLabels: {}

secret:
  dbWriter:
    name: fhir-storage-writer-database-secret
    key: FHIR_STORAGE_WRITER_DB_PASSWORD
    propPath: spring/datasource/password
  dbWriterDdl:
    name: fhir-storage-writer-ddl-database-secret
    key: FHIR_STORAGE_WRITER_DDL_DB_PASSWORD
    propPath: spring/liquibase/password

# Environment Variables to be defined
customEnvVars:
  DB_URL: "jdbc:postgresql://pgbouncer:5432/fhir-storage"
  DB_USER: fhir-storage-writer
  SPRING_LIQUIBASE_USER: fhir-storage-writer-ddl
  CONFIG_HAPI_CLIENT_THREADS_CORE_SIZE: 2
  CONFIG_HAPI_CLIENT_THREADS_MAX_SIZE: 2
  CONFIG_HAPI_CLIENT_THREADS_QUEUE_CAPACITY: 500

# Extra labels for deployments
deploymentLabels: {}

# Define custom Container Entrypoint and Arguments (e.g. JVM Tuning)
# If not given, the Entrypoint defined in Dockerfile will be used
application:
  entrypoint: ["java"]
  parameters: ["-XX:ActiveProcessorCount=2", "-XX:MaxRAMPercentage=80.0", "-XX:+TieredCompilation", "-XX:+UseSerialGC", "-jar", "/app.jar"]

# Define Image Pull Secrets if using private registry
imagePullSecrets: []
imagePullPolicy: IfNotPresent
nameOverride: "fhir-storage-writer"
fullnameOverride: "fhir-storage-writer"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# Annotations for Workload
annotations: {}

# Annotations for Pods
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/actuator/prometheus"
  prometheus.io/port: "8080"

# Pod Security Context - applies to all containers in a Pod
podSecurityContext:
  # The GID to tell the Kubelet to modify permissions of a volume owned by a pod
  fsGroup: 10000
  # Determines when to apply fsGroup actions - "Always" is the default
  fsGroupChangePolicy: "OnRootMismatch"
  # Which GID container process is assigned
  runAsGroup: 10000
  # Determine whether container process starts as root (UID 0)
  runAsNonRoot: true
  # Which UID container process is assigned
  runAsUser: 10000

# Container Security Context for a single container - Takes precedence over PodSecurityContext
securityContext:
  #defines whether container can be granted privileges beyond the parent process spawing the process
  allowPrivilegeEscalation: false
  #Define whether the container has privileged access e.g. CAP_SYS_ADMIN capability and SELinux spc_t type
  privileged: false
  #Usually no longer required. Determines whether /proc is masked to the container. Do not mount /proc from a host to a container
  procMount: Default
  # The SELinux context to be applied to the container. Must not be explicitly set to Unconfined.
  seccompProfile:
    type: "RuntimeDefault"
  #Which GID container process is assigned
  runAsGroup: 10000
  # Determine whether container process starts as root (UID 0)
  runAsNonRoot: true
  #Which UID container process is assigned
  runAsUser: 10000
  # Sets the file system as read-only
  readOnlyRootFilesystem: true
  #Ability to remove and /or add Linux Capabilities
  capabilities:
    drop:
      - all

service:
  type: ClusterIP
  ports:
    http: 8080

# Default Resources
resources:
  limits:
    memory: "1Gi"
  requests:
    cpu: "200m"
    memory: "256Mi"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

istio:
  enable: true
  validateJwt: false
