spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fhir-storage
    username: fhir-storage-writer
    password: JkuqJadzhfKQ5CWSTsH5

server:
  port: 9090


logging:
  level:
    de.gematik.demis.storage: DEBUG
    org:
      hibernate:
        SQL: DEBUG
#        orm.jdbc.bind: trace
  pattern:
    level: "%X{traceId:-}/%X{spanId:-} -%5p"

fss:
  hapi:
    url: http://localhost:9999/fhir
    cron: "*/10 * * * * *"