info:
  app:
    name: @project.name@
    version: @project.version@

spring:
  config:
    import: classpath:/base-config-application.yaml

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    open-in-view: false

  liquibase:
    enabled: ${SPRING_LIQUIBASE_ENABLED:false}
    change-log: classpath:db/changelog.yaml
    user: fhir-storage-writer-ddl
    url: ${DB_URL}

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

    hikari:
      minimum-idle: 2
      maximum-pool-size: 10

fss:
  writer:
    context-path: ${API_ENTRYPOINT:/}
