fullnameOverride: fhir-storage-writer
service:
  type: ClusterIP
  ports:
    http: 8080
istio:
  virtualService:
    gateways: {}
    http:
      match:
        - uri:
            prefix: /notification-clearing-api
      rewrite:
        uri: /notification-clearing-api
    hosts: {}
  subsets:
    main:
      version: 1.0.0
      weight: "100"
# activate Traffic mirroring, also called shadowing with the following lines
#      mirror:
#        version: 1.1.0
#        mirrorPercentage: 0
